name: MLenv
channels:
  - anaconda
  - conda-forge
dependencies:
  - opencv
  - nltk
  - regex
  - imageio
  - pillow
  - scikit-image
  - scikit-learn==0.23.0
  - seaborn
  - matplotlib
  - python=3
  - scipy
  - imbalanced-learn
  - jupyter
  - numpy
  - xgboost
  - pandas
  - mlxtend
  - catboost
